services:
  php:
    image: php:8.2-apache
    container_name: php_container
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./backend/src:/var/www/src
      - ./backend/public:/var/www/html
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
  db:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vacation_request_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/database/vacation_request_db.sql:/docker-entrypoint-initdb.d/vacation_request_db.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  frontend:
    container_name: react_frontend_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - php

volumes:
  db_data:
