services:
  php:
    image: php:8.2-apache
    container_name: php_container
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/src
      - ./public:/var/www/html
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
  db:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: assessment_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/assessment_db.sql:/docker-entrypoint-initdb.d/assessment_db.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
